export const getProductFields = (categoryOptions = [], product = {}) => [
  {
    name: "name",
    label: "Product Name",
    type: "text",
    placeholder: "Enter new Product name",
    required: true,
    defaultValue: product.name || "",
  },
  {
    name: "description",
    label: "Product Description",
    type: "text",
    placeholder: "Enter description",
    required: true,
    defaultValue: product.description || "",
  },
  {
    name: "categoryId",
    label: "Category",
    type: "select",
    placeholder: "Select category",
    required: true,
    options: categoryOptions,
    defaultValue: product.categoryId || "",
  },
  {
    name: "offerPercent",
    label: "Offer Percent",
    type: "number",
    placeholder: "Enter offer percent",
    required: true,
    defaultValue: product.offerPercent || 0,
  },
  {
    name: "returnPolicy",
    label: "Return Policy",
    type: "select",
    placeholder: "Select an option",
    required: false,
    options: [
      { label: "Yes", value: true },
      { label: "No", value: false },
    ],
    defaultValue: product.returnPolicy || "",
  },
  {
    name: "COD",
    label: "Cash On Delivery available?",
    type: "select",
    placeholder: "Select an option",
    required: false, 
    options: [
      { label: "Yes", value: true },
      { label: "No", value: false },
    ],
    defaultValue: product.COD !== undefined ? product.COD : "",
  },
  {
    name: "warranty",
    label: "Warranty",
    type: "text",
    placeholder: "Enter warranty details",
    required: true,
    defaultValue: product.warranty || "",
  },
  {
    name: "model",
    label: "Model",
    type: "text",
    placeholder: "Enter model",
    required: true,
    defaultValue: product.model || "",
  },
  {
    name: "size",
    label: "Size",
    type: "text",
    placeholder: "Enter size",
    required: true,
    defaultValue: product.size || "",
  },
  {
    name: "ram",
    label: "Ram capacity in GB",
    type: "number",
    placeholder: "Enter ram",
    required: true,
    defaultValue: product.ram || 0,
  },
  {
    name: "storage",
    label: "Storage capacity in GB",
    type: "number",
    placeholder: "Enter storage",
    required: true,
    defaultValue: product.storage || 0,
  },
  {
    name: "stock",
    label: "Stock count",
    type: "number",
    placeholder: "Enter stock",
    required: true,
    defaultValue: product.stock || 0,
  },
  {
    name: "price",
    label: "Price",
    type: "number",
    placeholder: "Enter product price",
    required: true,
    defaultValue: product.price || 0,
  },
  {
    name: "network",
    label: "Network",
    type: "text",
    placeholder: "Enter network",
    required: true,
    defaultValue: product.network || "",
  },
];
