name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
      env:
        VITE_API_URL: ${{ secrets.VITE_API_URL }}

    - name: List files in dist folder
      run: ls -l dist
    
    - name: Cache build artifacts
      uses: actions/cache@v4
      with:
        path: dist/
        key: ${{ runner.os }}-build-${{ github.sha }}
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Navigate to project directory
          cd ~/frontend/_work/mobilify-react-app/mobilify-react-app
          
          # Pull latest changes
          git pull origin master
          
          # Install dependencies
          npm ci
          
          # Build the application
          npm run build
          
          # Check if build was successful
          if [ -d "dist" ]; then
            echo "Build successful"
            
            # If using PM2 to serve the static files
            if pm2 show frontend-serve > /dev/null; then
              pm2 restart frontend-serve
            else
              pm2 serve dist 3000 --name frontend-serve --spa
            fi
            
            pm2 save
          else
            echo "Build failed - dist directory not found"
            exit 1
          fi